Student student = new Student();
Instructor instructor = new Instructor();
//StudentManager.CreateDB();
////StudentManager.CreateStudentTable();
//StudentManager.CreateStudent(student);
//StudentManager.UpdateStudent();
//StudentManager.DeleteStudent();
//StudentManager.GetAllStudents();
//StudentManager.GetStudents();
//InstructorManager.CreateInstructors(instructor);
//InstructorManager.DeleteInstructor();
//InstructorManager.GetStudentAndSupervisors();
InstructorManager.GetStudentsAndSupervisorsUsingFullJoin();